package wg.media.screen.model.datasea.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTypeFirstId(java.lang.Integer typeFirstId) {
		set("typeFirstId", typeFirstId);
	}
	
	public java.lang.Integer getTypeFirstId() {
		return getInt("typeFirstId");
	}

	public void setTypeSecondId(java.lang.Integer typeSecondId) {
		set("typeSecondId", typeSecondId);
	}
	
	public java.lang.Integer getTypeSecondId() {
		return getInt("typeSecondId");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
	}
	
	public java.lang.String getImgUrl() {
		return getStr("imgUrl");
	}

	public void setVedioUrl(java.lang.String vedioUrl) {
		set("vedioUrl", vedioUrl);
	}
	
	public java.lang.String getVedioUrl() {
		return getStr("vedioUrl");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setAuthorId(java.lang.String authorId) {
		set("authorId", authorId);
	}
	
	public java.lang.String getAuthorId() {
		return getStr("authorId");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setTypeIds(java.lang.String typeIds) {
		set("typeIds", typeIds);
	}
	
	public java.lang.String getTypeIds() {
		return getStr("typeIds");
	}

	public void setUseTime(java.lang.String useTime) {
		set("useTime", useTime);
	}
	
	public java.lang.String getUseTime() {
		return getStr("useTime");
	}

	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	public java.lang.String getMaterial() {
		return getStr("material");
	}

	public void setStepImgs(java.lang.String stepImgs) {
		set("stepImgs", stepImgs);
	}
	
	public java.lang.String getStepImgs() {
		return getStr("stepImgs");
	}

	public void setStepText(java.lang.String stepText) {
		set("stepText", stepText);
	}
	
	public java.lang.String getStepText() {
		return getStr("stepText");
	}

	public void setTips(java.lang.String tips) {
		set("tips", tips);
	}
	
	public java.lang.String getTips() {
		return getStr("tips");
	}

	public void setVisits(java.lang.Integer visits) {
		set("visits", visits);
	}
	
	public java.lang.Integer getVisits() {
		return getInt("visits");
	}

	public void setCollections(java.lang.Integer collections) {
		set("collections", collections);
	}
	
	public java.lang.Integer getCollections() {
		return getInt("collections");
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("linkUrl", linkUrl);
	}
	
	public java.lang.String getLinkUrl() {
		return getStr("linkUrl");
	}

	public void setAddTime(java.lang.String addTime) {
		set("addTime", addTime);
	}
	
	public java.lang.String getAddTime() {
		return getStr("addTime");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

}
