package wg.media.screen.model.datasea.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setFId(java.lang.Integer fId) {
		set("f_id", fId);
	}
	
	public java.lang.Integer getFId() {
		return getInt("f_id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setFollows(java.lang.String follows) {
		set("follows", follows);
	}
	
	public java.lang.String getFollows() {
		return getStr("follows");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

}
