package wg.media.screen.model.datasea.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setRole(java.lang.Integer role) {
		set("role", role);
	}
	
	public java.lang.Integer getRole() {
		return getInt("role");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	public void setNative(java.lang.String _native) {
		set("native", _native);
	}
	
	public java.lang.String getNative() {
		return getStr("native");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}
	
	public java.lang.String getNation() {
		return getStr("nation");
	}

	public void setBirth(java.lang.String birth) {
		set("birth", birth);
	}
	
	public java.lang.String getBirth() {
		return getStr("birth");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setLon(java.lang.String lon) {
		set("lon", lon);
	}
	
	public java.lang.String getLon() {
		return getStr("lon");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
