package wg.media.screen.model.datasea;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("follow", "f_id", Follow.class);
		arp.addMapping("food", "id", Food.class);
		arp.addMapping("foodTypeFirst", "id", FoodTypeFirst.class);
		arp.addMapping("foodTypeSecond", "id", FoodTypeSecond.class);
		arp.addMapping("menu", "id", Menu.class);
		arp.addMapping("menuTypeFirst", "id", MenuTypeFirst.class);
		arp.addMapping("menuTypeSecond", "id", MenuTypeSecond.class);
		arp.addMapping("user", "user_id", User.class);
	}
}

