package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	public static final Follow dao = new Follow().dao();
}
