package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseFoodTypeFirst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoodTypeFirst extends BaseFoodTypeFirst<FoodTypeFirst> {
	public static final FoodTypeFirst dao = new FoodTypeFirst().dao();
}
