package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseFoodTypeSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FoodTypeSecond extends BaseFoodTypeSecond<FoodTypeSecond> {
	public static final FoodTypeSecond dao = new FoodTypeSecond().dao();
}
