package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseFood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Food extends BaseFood<Food> {
	public static final Food dao = new Food().dao();
}
