package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseMenuTypeFirst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuTypeFirst extends BaseMenuTypeFirst<MenuTypeFirst> {
	public static final MenuTypeFirst dao = new MenuTypeFirst().dao();
}
