package wg.media.screen.model.datasea;

import wg.media.screen.model.datasea.base.BaseMenuTypeSecond;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuTypeSecond extends BaseMenuTypeSecond<MenuTypeSecond> {
	public static final MenuTypeSecond dao = new MenuTypeSecond().dao();
}
